services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8443:443"          # HTTPS
      - "8081:80"         
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/fullchain.pem:/etc/ssl/fullchain.pem:ro
      - ./ssl/privkey.pem:/etc/ssl/privkey.pem:ro




