services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  registration:
    build:
      context: ..
      dockerfile: Dockerfile
    command: uvicorn services.registration.app:app --host 0.0.0.0 --port 8001
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - RUN_DB_MIGRATIONS=true
      - AES_MASTER_KEY=${AES_MASTER_KEY}     # <-- ADD THIS
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - registration

volumes:
  pgdata:
