# infra/docker-compose.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: evote
      POSTGRES_USER: evote
      POSTGRES_PASSWORD: StrongLocalPassword123
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      # keep these literal so they don't depend on shell expansion
      test: ["CMD-SHELL", "pg_isready -U evote -d evote"]
      interval: 10s
      timeout: 5s
      retries: 5

  registration:
    build:
      context: ..
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn services.registration.app:app --host 0.0.0.0 --port 8001
    # Load secrets and DATABASE_URL from .env (file sits next to this compose file)
    env_file:
      - .env
    # Keep explicit envs we need; values come from .env at runtime
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RUN_DB_MIGRATIONS: "true"
      AES_MASTER_KEY: ${AES_MASTER_KEY}
      MFA_ENC_KEY_HEX: ${MFA_ENC_KEY_HEX}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"

volumes:
  pgdata: {}