services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: evote
      POSTGRES_USER: evote
      POSTGRES_PASSWORD: evote_pw
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U evote -d evote']
      interval: 10s
      timeout: 5s
      retries: 5

  registration:
    build:
      context: ..
      dockerfile: Dockerfile
    command: uvicorn services.registration.app:app --host 0.0.0.0 --port 8001
    environment:
      DATABASE_URL: postgresql+psycopg2://evote:evote_pw@db:5432/evote
      RUN_DB_MIGRATIONS: "true"
      AES_MASTER_KEY: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"