name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI placeholder - replace with real tests later"
